name: Build, Lint, and Test
description: A composite action to build, lint, and test the project

inputs:
  github-token:
    description: "GitHub token for PR comments and artifact access"
    required: true

runs:
  using: composite
  steps:
    - name: Build packages
      shell: bash
      run: pnpm -r build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-packages
        if-no-files-found: error
        retention-days: 1
        path: packages/*/dist/

    - name: Lint code
      shell: bash
      run: pnpm -r lint

    - name: Run tests
      shell: bash
      run: pnpm -r test -- --ci --coverage

    # Use our coverage reporter action for comprehensive coverage analysis
    - name: Generate coverage report
      uses: deresegetachew/systemcraft-stack-actions/actions/coverage-reporter@main
      with:
        coverage-command: 'pnpm -r test'
        coverage-file: 'coverage-summary.json'
        output-dir: 'coverage-artifacts'
        enable-pr-comments: 'true'
        minimum-coverage: '70'
        github-token: ${{ inputs.github-token }}
      
